name: GitHub Actions CI/CD Pipeline for Terraform Deployment
run-name: ${{ github.actor }} the user that triggerd the pipeline

on:
  push:
    branches:
      - 'main'

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  build-infra:
    name: terraform deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ./Terraform
      - name: Terraform validate
        id: validate
        run: terraform validate
        working-directory: ./Terraform
      - name: Terraform Refresh
        run: terraform refresh
        working-directory: ./Terraform
      - name: Terraform plan
        id: plan
        run: terraform plan
        working-directory: ./Terraform
      - name: Terraform apply
        id: apply
        run: terraform apply --auto-approve
        working-directory: ./Terraform
      - name: Get Load Balancer DNS Name
        run: |
          # Fetch and echo the DNS name from Terraform output
          echo "The DNS address of the Load Balancer is $(terraform output -raw lb_address)"